//
//  ConsolidatedTests.swift
//  ft_hamTests
//
//  Consolidated suite generated by automation to combine all XCTest cases
//

import XCTest
@testable import ft8_ham
import MapKit
import SwiftUI

// MARK: - FT8ViewModelTests (original)
@MainActor
final class FT8ViewModelTests: XCTestCase {

    var viewModel: FT8ViewModel!

    override func setUp() async throws {
        try await super.setUp()
        viewModel = FT8ViewModel(txMessages: [], rxMessages: [])
    }

    override func tearDown() async throws {
        viewModel = nil
        try await super.tearDown()
    }

    func testGenerateMessagesWithDefaultValues() {
        viewModel.callsign = "EA1AAA"
        viewModel.locator = "IM99"
        viewModel.dxCallsign = "K1ABC"
        viewModel.dxLocator = "FN31"
        viewModel.lastSentSNR = 10

        let messages = viewModel.generateMessages()

        XCTAssertEqual(messages.count, 7)
        XCTAssertTrue(messages[0].contains("EA1AAA"))
        XCTAssertTrue(messages[1].contains("K1ABC"))
        XCTAssertTrue(messages[2].contains("+10"))
    }
    
    func testSettingsLoadedReturnsTrueOnlyIfCallsignAndLocatorSet() {
        viewModel.callsign = ""
        viewModel.locator = ""
        XCTAssertFalse(viewModel.settingsLoaded)

        viewModel.callsign = "EA1AAA"
        XCTAssertFalse(viewModel.settingsLoaded)

        viewModel.locator = "IM99"
        XCTAssertTrue(viewModel.settingsLoaded)
    }

    func testWorkedLocatorsAreUpdated() {
        viewModel.receivedMessages = [
            FT8Message(text: "CQ EA4IQL IN80", mode: .ft8, measuredSNR: -12, frequency: 1500.0, timeOffset: 0.1, isTX: false),
            FT8Message(text: "CQ EA5TTT IN15", mode: .ft8, measuredSNR: -12, frequency: 1500.0, timeOffset: 0.1, isTX: false),
            FT8Message(text: "CQ EA1QQQ IN19", mode: .ft8, measuredSNR: -12, frequency: 1500.0, timeOffset: 0.1, isTX: false),
        ]

        for msg in viewModel.receivedMessages {
            if let dx = msg.locator, !dx.isEmpty, !viewModel.workedLocators
                .contains(dx) {
                viewModel.workedLocators.append(dx)
            }
        }

        XCTAssertEqual(viewModel.workedLocators.count, 3)
        XCTAssertTrue(viewModel.workedLocators.contains("IN15"))
        XCTAssertTrue(viewModel.workedLocators.contains("IN19"))
    }

    func testDecodeFromWavAppendsMessages() {
        let message1 = FT8Message.decode(text: "EA1AAA K1ABC +10", mode: .ft8, snr: -10, frequency: 1500, timeOffset: 0.1)
        let message2 = FT8Message.decode(text: "K1ABC EA1AAA -12", mode: .ft8, snr: -12, frequency: 1501, timeOffset: 0.2)
        
        // Simulate engine decoding by setting wavURL to nil (so decode returns empty array) and manually appending
        viewModel.receivedMessages = []
        viewModel.workedLocators = []

        viewModel.receivedMessages.append(message1)
        viewModel.receivedMessages.append(message2)

        for msg in viewModel.receivedMessages {
            if let dx = msg.dxLocator, !dx.isEmpty, !viewModel.workedLocators
                .contains(dx) {
                viewModel.workedLocators.append(dx)
            }
        }

        XCTAssertEqual(viewModel.receivedMessages.count, 2)
        XCTAssertTrue(viewModel.workedLocators.isEmpty || viewModel.workedLocators.count <= 2)
    }
    
    func testClearReceivedMessages() {
        viewModel.receivedMessages = [
            FT8Message(text: "Message 1", mode: .ft8),
            FT8Message(text: "Message 2", mode: .ft8)
        ]

        viewModel.clearReceived()

        XCTAssertTrue(viewModel.receivedMessages.isEmpty)
    }

    func testClearTransmittedMessages() {
        viewModel.transmittedMessages = [
            FT8Message(text: "TX 1", mode: .ft8),
            FT8Message(text: "TX 2", mode: .ft8)
        ]

        viewModel.clearTransmitted()

        XCTAssertTrue(viewModel.transmittedMessages.isEmpty)
    }

    func testClearLastDecodedMessage() {
        viewModel.decodedMessage = FT8Message(text: "Last decoded", mode: .ft8)

        viewModel.clearLastMessage()

        XCTAssertNil(viewModel.decodedMessage)
    }

}

// MARK: - AudioManagerTests
final class AudioManagerTests: XCTestCase {
    func testInitInPreviewMode() {
        let am = AudioManager(waterfallFFTSize: 1024, sampleRate: 12000, isTestMode: true)
        XCTAssertEqual(am.sampleRate, 12000)
        XCTAssertEqual(am.waterfallFFTSize, 1024)
    }

    func testPlayAndStopPlaybackNoCrash() {
        let am = AudioManager(waterfallFFTSize: 256, sampleRate: 12000, isTestMode: true)

        var floats = [Float](repeating: 0.0, count: 16)
        floats[0] = 1.0
        let data = Data(bytes: &floats, count: floats.count * MemoryLayout<Float>.size)

        am.playAudio(data)
        am.stopPlayback()
        XCTAssertFalse(am.isPlaying)
    }
}

// MARK: - FT8ViewModelUnitTests + Integration + E2E
@MainActor
final class FT8ViewModelUnitTests: XCTestCase {

    var viewModel: FT8ViewModel!

    override func setUp() async throws {
        try await super.setUp()
        viewModel = FT8ViewModel()
        viewModel.autoSequencingEnabled = false
        viewModel.callsign = "EA1AAA"
        viewModel.locator = "IN81aa"
        viewModel.selectedBand = .band20m
        viewModel.clearReceived()
        viewModel.clearTransmitted()
    }

    override func tearDown() async throws {
        viewModel = nil
        try await super.tearDown()
    }

    func testInitialValues() async {
        XCTAssertEqual(viewModel.callsign, "EA1AAA")
        XCTAssertEqual(viewModel.locator, "IN81aa")
        XCTAssertEqual(viewModel.selectedBand, .band20m)
        XCTAssertFalse(viewModel.autoSequencingEnabled)
    }

    func testAppendingRxMessage() async {
        let msg = FT8Message(
            text: "CQ EA1AAA IN81aa",
            mode: .ft8,
            isRealtime: true,
            measuredSNR: 10,
            frequency: 14074_000,
            band: viewModel.selectedBand,
            allowsReply: true
        )

        viewModel.receivedMessages.append(msg)

        XCTAssertEqual(viewModel.receivedMessages.count, 1)
        XCTAssertEqual(viewModel.receivedMessages.first?.text, "CQ EA1AAA IN81aa")
    }

    func testAppendingTxMessage() async {
        let msg = FT8Message(
            text: "RR73 EA1AAA IN81aa",
            mode: .ft8,
            isRealtime: true,
            measuredSNR: 15,
            frequency: 14074_000,
            isTX: true,
            band: viewModel.selectedBand,
            allowsReply: false
        )

        viewModel.transmittedMessages.append(msg)

        XCTAssertEqual(viewModel.transmittedMessages.count, 1)
        XCTAssertTrue(viewModel.transmittedMessages.first!.isTX)
    }
}

@MainActor
final class FT8ViewModelIntegrationTests: XCTestCase {

    var viewModel: FT8ViewModel!

    override func setUp() async throws {
        try await super.setUp()
        viewModel = FT8ViewModel()
        viewModel.autoSequencingEnabled = true
        viewModel.callsign = "EA1AAA"
        viewModel.locator = "IN81aa"
        viewModel.selectedBand = .band20m
    }

    override func tearDown() async throws {
        viewModel = nil
        try await super.tearDown()
    }

    func testAutoSequencingEnabled() async {
        XCTAssertTrue(viewModel.autoSequencingEnabled)
    }

    func testLockingDXCallsign() async {
        let msg = FT8Message(
            text: "CQ EA2BBB IN81bb",
            mode: .ft8,
            isRealtime: true,
            band: viewModel.selectedBand
        )

        viewModel.receivedMessages.append(msg)
//        viewModel.lockedDXCallsign = "EA2BBB"

//        XCTAssertEqual(viewModel.lockedDXCallsign, "EA2BBB")
    }
}

@MainActor
final class FT8ViewModelE2ETests2: XCTestCase {

    var viewModel: FT8ViewModel!

    override func setUp() async throws {
        try await super.setUp()
        viewModel = FT8ViewModel()
        viewModel.autoSequencingEnabled = true
        viewModel.callsign = "EA1AAA"
        viewModel.locator = "IN81aa"
        viewModel.selectedBand = .band20m
    }

    override func tearDown() async throws {
        viewModel = nil
        try await super.tearDown()
    }

    func testFullTxRxCycle() async {
        viewModel.clearReceived()
        viewModel.clearTransmitted()
        
        let rxMsg = FT8Message(
            text: "CQ EA1AAA IN81aa",
            mode: .ft8,
            isRealtime: true,
            measuredSNR: 12,
            frequency: 14074_000,
            band: viewModel.selectedBand
        )

        viewModel.receivedMessages.append(rxMsg)

        let txMsg = FT8Message(
            text: "RR73 EA2BBB IN81bb",
            mode: .ft8,
            isRealtime: true,
            measuredSNR: 15,
            frequency: 14074_000,
            isTX: true,
            band: viewModel.selectedBand
        )

        viewModel.transmittedMessages.append(txMsg)

        XCTAssertEqual(viewModel.receivedMessages.count, 1)
        XCTAssertEqual(viewModel.transmittedMessages.count, 1)
        XCTAssertEqual(viewModel.transmittedMessages.first?.isTX, true)
        XCTAssertEqual(viewModel.receivedMessages.first?.text, "CQ EA1AAA IN81aa")
    }
}

// MARK: - FT8ViewModelAdditionalTests (uses mocks kept in project)
//@MainActor
//final class FT8ViewModelAdditionalTests: XCTestCase {
//    var viewModel: FT8ViewModel!
//    var mockAudio: MockAudioManager!
//    var mockEngine: MockFT8Engine!
//    var mockSlots: MockSlotManager!
//
//    override func setUp() async throws {
//        try await super.setUp()
//        mockAudio = MockAudioManager()
//        mockEngine = MockFT8Engine()
//        mockSlots = MockSlotManager()
//
//        viewModel = FT8ViewModel(
//            txMessages: [],
//            rxMessages: []
//        )
//    }
//
//    override func tearDown() async throws {
//        viewModel = nil
//        mockAudio = nil
//        mockEngine = nil
//        mockSlots = nil
//        try await super.tearDown()
//    }
//
//    func testReplyPreparesReply() {
//        let msg = FT8Message(text: "EA1AAA K1ABC +10", mode: .ft8, isRealtime: true)
//        viewModel.callsign = "K1ABC"
//        viewModel.locator = "IM99"
//        viewModel.reply(to: msg)
//
//        XCTAssertEqual(viewModel.dxCallsign, "EA1AAA")
//        XCTAssertEqual(viewModel.dxLocator, "IM99")
//        XCTAssertEqual(viewModel.selectedMessageIndex, 1)
//        XCTAssertFalse(viewModel.allMessages.isEmpty)
//    }
//
//    func testStartProgressBarUTCUpdatesProgress() async {
//        viewModel.isFT4 = false
//        viewModel.startProgressBarUTC()
//        try? await Task.sleep(nanoseconds: 200_000_000)
//        XCTAssertGreaterThanOrEqual(viewModel.cycleProgress, 0.0)
//        XCTAssertLessThanOrEqual(viewModel.cycleProgress, 1.0)
//    }
//
//    func testToggleTransmitStartsTXLoopAndPlays() async {
//        viewModel.callsign = "EA1AAA"
//        viewModel.locator = "IM99"
//        viewModel.allMessages = ["CQ EA1AAA IM99"]
//        viewModel.selectedMessageIndex = 0
//        viewModel.selectedBand = .band10m
//
//        XCTAssertFalse(viewModel.transmitLoopActive)
//
//        viewModel.toggleTransmit()
//        XCTAssertTrue(viewModel.transmitLoopActive)
//
//        try? await Task.sleep(nanoseconds: 15_000_000_000)
//
//        XCTAssertTrue(mockEngine.generateCalled)
//        XCTAssertTrue(mockAudio.playCalled)
//        XCTAssertEqual(viewModel.transmittedMessages.count, 1)
//
//        viewModel.toggleTransmit()
//        XCTAssertFalse(viewModel.transmitLoopActive)
//    }
//
//    func testDecodeFromWavUsesEngineAndAppendsMessages() async {
//        viewModel.wavURL = nil
//        viewModel.decodeFromWav()
//        XCTAssertTrue(mockEngine.decodeCalled)
//        XCTAssertGreaterThanOrEqual(viewModel.receivedMessages.count, 1)
//        XCTAssertNotNil(viewModel.decodedMessage)
//    }
//}

// MARK: - FT8ViewModelComprehensiveTests
@MainActor
final class FT8ViewModelComprehensiveTests: XCTestCase {

    var viewModel: FT8ViewModel!

    override func setUp() async throws {
        try await super.setUp()
        viewModel = FT8ViewModel(txMessages: [], rxMessages: [])
    }

    override func tearDown() async throws {
        viewModel = nil
        try await super.tearDown()
    }

    func testSettingsLoadedWithVariousCombinations() {
        // Empty callsign and locator
        viewModel.callsign = ""
        viewModel.locator = ""
        XCTAssertFalse(viewModel.settingsLoaded)
        
        // Only callsign
        viewModel.callsign = "EA1AAA"
        viewModel.locator = ""
        XCTAssertFalse(viewModel.settingsLoaded)
        
        // Only locator
        viewModel.callsign = ""
        viewModel.locator = "IM99"
        XCTAssertFalse(viewModel.settingsLoaded)
        
        // Both set
        viewModel.callsign = "EA1AAA"
        viewModel.locator = "IM99"
        XCTAssertTrue(viewModel.settingsLoaded)
    }

    func testGenerateMessagesFT8AndFT4() {
        viewModel.callsign = "EA1AAA"
        viewModel.locator = "IM99"
        viewModel.dxCallsign = "K1ABC"
        viewModel.dxLocator = "FN31"
        viewModel.lastSentSNR = 10
        
        let ft8Messages = viewModel.generateMessages()
        XCTAssertEqual(ft8Messages.count, 7)
        XCTAssertTrue(ft8Messages[0].contains("EA1AAA"))
        XCTAssertTrue(ft8Messages[1].contains("K1ABC"))
        XCTAssertTrue(ft8Messages[2].contains("+10"))

    }

    func testGenerateMessagesWithEmptyDXValues() {
        viewModel.callsign = "EA1AAA"
        viewModel.locator = "IM99"
        viewModel.dxCallsign = ""
        viewModel.dxLocator = ""
        viewModel.lastSentSNR = -5
        
        let messages = viewModel.generateMessages()
        XCTAssertTrue(messages[1].contains("XXXXXX"))
        XCTAssertTrue(messages[1].contains("EA1AAA"))
        XCTAssertTrue(messages[2].contains("-05"))
    }

    func testReplyUpdatesDXAndPower() {
        viewModel.callsign = "EA1AAA"
        viewModel.locator = "IM99"
        
        let message = FT8Message(
            text: "CQ K1ABC FN31",
            mode: .ft8,
            measuredSNR: 12,
            frequency: 1400,
            isTX: false
        )
        viewModel.reply(to: message)
        
        XCTAssertEqual(viewModel.dxCallsign, "K1ABC")
        XCTAssertEqual(viewModel.dxLocator, "FN31")
        XCTAssertEqual(viewModel.qsoManager.lastSentSNR, 12)
        XCTAssertEqual(viewModel.frequency, 1400)
        XCTAssertEqual(viewModel.selectedMessageIndex, 1)
    }

    func testWorkedLocatorsPopulateFromMessages() {
        let msg1 = FT8Message(
            text: "EA1AAA K1ABC +10",
            mode: .ft8,
            isRealtime: true,
            measuredSNR: -12.0,
            frequency: 1500.0,
            timeOffset: 0.1,
            isTX: false
        )
        
        viewModel.receivedMessages = [msg1]
        XCTAssertFalse(viewModel.receivedMessages.isEmpty)
    }

//    func testDecodeFromWavAppendsMessages() {
//        viewModel.wavURL = nil
//        viewModel.decodeFromWav()
//        XCTAssertNotNil(viewModel.receivedMessages)
//    }

//    func testTransmitMessageValidatesCallsignAndLocator() async {
//        viewModel.callsign = "EA1AAA"
//        viewModel.locator = "IM99"
//        viewModel.allMessages = ["CQ EA1AAA IM99"]
//        viewModel.selectedMessageIndex = 0
//        viewModel.selectedBand = .band10m
//        viewModel.isFT4 = false
//        viewModel.transmitLoopActive = true
//
//        viewModel.startSequencer()
//        
//        try? await Task.sleep(nanoseconds: 30_500_000_000) // Safe waiting depending on the time the test is triggered
//        
//        XCTAssertEqual(viewModel.transmittedMessages.count, 1)
//        if(!viewModel.transmittedMessages.isEmpty){
//            XCTAssertEqual(viewModel.transmittedMessages[0].text, "CQ EA1AAA IM99")
//        }
//        
//        viewModel.stopSequencer()
//    }

    func testTransmitMessageWithInvalidCallsignOrLocator() async {
        viewModel.callsign = ""
        viewModel.locator = ""
        viewModel.allMessages = ["CQ ??? ???"]
        viewModel.selectedMessageIndex = 0
        viewModel.transmitLoopActive = true

        _ = viewModel.generateMessages()
        
        XCTAssertTrue(viewModel.allMessages.isEmpty || viewModel.allMessages.contains(where: { $0.contains("?") }))
    }

    func testClearReceivedMessages() {
        viewModel.receivedMessages = [FT8Message(text: "1", mode: .ft8)]
        viewModel.clearReceived()
        XCTAssertTrue(viewModel.receivedMessages.isEmpty)
    }

    func testClearTransmittedMessages() {
        viewModel.transmittedMessages = [FT8Message(text: "TX", mode: .ft8)]
        viewModel.clearTransmitted()
        XCTAssertTrue(viewModel.transmittedMessages.isEmpty)
    }

    func testClearLastDecodedMessage() {
        viewModel.decodedMessage = FT8Message(text: "Last", mode: .ft8)
        viewModel.clearLastMessage()
        XCTAssertNil(viewModel.decodedMessage)
    }

//    func testStartProgressBarUpdatesCycleProgress() async throws {
//        viewModel.isFT4 = false
//        viewModel.startProgressBarUTC()
//        try await Task.sleep(nanoseconds: 100_000_000)
//        XCTAssertGreaterThanOrEqual(viewModel.cycleProgress, 0.0)
//        XCTAssertLessThanOrEqual(viewModel.cycleProgress, 1.0)
//    }
}

// MARK: - GridMapTests
final class GridMapTests: XCTestCase {
    func testGridPolygonValid() {
        let coords = MaidenheadGrid.gridPolygon(for: "IO91")
        XCTAssertNotNil(coords)
        XCTAssertEqual(coords?.count, 4)
        if let c = coords {
            XCTAssertTrue((-90...90).contains(c[0].latitude))
            XCTAssertTrue((-180...180).contains(c[0].longitude))
        }
    }

    func testGridPolygonInvalid() {
        XCTAssertNil(MaidenheadGrid.gridPolygon(for: "XX"))
    }
}

@MainActor
final class GridMapViewRenderingTests: XCTestCase {

    func testGridMapViewAddsPolygonAndAnnotation() {
        let mapView = MKMapView()
        let locatorsBinding = Binding<[String]>(
            get: { ["IN80"] },
            set: { _ in }
        )
        var trackingMode: MKUserTrackingMode = .none
        let trackingModeBinding = Binding<MKUserTrackingMode>(get: { trackingMode }, set: { trackingMode = $0 })
        let coordinator = GridMapView.Coordinator(locators: locatorsBinding, trackingMode: trackingModeBinding)

        let locators = ["IO91"]
        let countries: [CountryPair] = []
        let visibility = MapVisibility(grids: true, countryCircles: true, geodesics: true, annotations: true)

        coordinator.updateMap(mapView, locators: locators, countries: countries, visibility: visibility)

        XCTAssertFalse(mapView.overlays.isEmpty)
        XCTAssertFalse(mapView.annotations.isEmpty)

        let hasPolygon = mapView.overlays.contains { $0 is MKPolygon }
        XCTAssertTrue(hasPolygon)

        let annotation = mapView.annotations.first { !($0 is MKUserLocation) }
        XCTAssertNotNil(annotation)
        XCTAssertEqual(annotation?.title ?? "", "IO91")
    }

    func testRendererForPolygonCircleAndGeodesic() {
        let locatorsBinding = Binding<[String]>(
            get: { [] },
            set: { _ in }
        )
        var trackingMode: MKUserTrackingMode = .none
        let trackingModeBinding = Binding<MKUserTrackingMode>(get: { trackingMode }, set: { trackingMode = $0 })
        let coordinator = GridMapView.Coordinator(locators: locatorsBinding, trackingMode: trackingModeBinding)
        let mapView = MKMapView()

        let polygon = MKPolygon(coordinates: [
            CLLocationCoordinate2D(latitude: 0, longitude: 0),
            CLLocationCoordinate2D(latitude: 0, longitude: 1),
            CLLocationCoordinate2D(latitude: 1, longitude: 1),
            CLLocationCoordinate2D(latitude: 1, longitude: 0)
        ], count: 4)

        let circle = MKCircle(center: CLLocationCoordinate2D(latitude: 0, longitude: 0), radius: 1000)

        let geodesic = MKGeodesicPolyline(coordinates: [
            CLLocationCoordinate2D(latitude: 0, longitude: 0),
            CLLocationCoordinate2D(latitude: 10, longitude: 10)
        ], count: 2)

        let polygonRenderer = coordinator.mapView(mapView, rendererFor: polygon)
        XCTAssertTrue(polygonRenderer is MKPolygonRenderer)

        let circleRenderer = coordinator.mapView(mapView, rendererFor: circle)
        XCTAssertTrue(circleRenderer is MKCircleRenderer)

        let geoRenderer = coordinator.mapView(mapView, rendererFor: geodesic)
        XCTAssertTrue(geoRenderer is MKPolylineRenderer)
    }

    func testCoordinatorDoesNotRedrawIfHashUnchanged() {
        let mapView = MKMapView()
        let locatorsBinding = Binding<[String]>(
            get: { ["IN80"] },
            set: { _ in }
        )
        var trackingMode: MKUserTrackingMode = .none
        let trackingModeBinding = Binding<MKUserTrackingMode>(get: { trackingMode }, set: { trackingMode = $0 })
        let coordinator = GridMapView.Coordinator(locators: locatorsBinding, trackingMode: trackingModeBinding)

        let locators = ["IO91"]
        let visibility = MapVisibility(grids: true, countryCircles: true, geodesics: true, annotations: true)

        coordinator.updateMap(mapView, locators: locators, countries: [], visibility: visibility)
        let overlayCount = mapView.overlays.count

        coordinator.updateMap(mapView, locators: locators, countries: [], visibility: visibility)
        XCTAssertEqual(mapView.overlays.count, overlayCount)
    }

    func testFitAllSetsVisibleMapRect() {
        let mapView = MKMapView()
        let locatorsBinding = Binding<[String]>(
            get: { ["IO91", "IN80"] },
            set: { _ in }
        )
        var trackingMode: MKUserTrackingMode = .none
        let trackingModeBinding = Binding<MKUserTrackingMode>(get: { trackingMode }, set: { trackingMode = $0 })
        let coordinator = GridMapView.Coordinator(locators: locatorsBinding, trackingMode: trackingModeBinding)

        let locators = ["IO91", "IN80"]
        let visibility = MapVisibility(grids: true, countryCircles: true, geodesics: true, annotations: true)
        coordinator.updateMap(mapView, locators: locators, countries: [], visibility: visibility)

        XCTAssertFalse(mapView.visibleMapRect.isNull)
    }
}

// ============================================================
// MARK: - MapHelpers Geometry Tests
// ============================================================

final class MapHelpersTests: XCTestCase {

    func testQuadraticBezierReturnsCorrectNumberOfPoints() {
        let start = MKMapPoint(CLLocationCoordinate2D(latitude: 0, longitude: 0))
        let control = MKMapPoint(CLLocationCoordinate2D(latitude: 5, longitude: 10))
        let end = MKMapPoint(CLLocationCoordinate2D(latitude: 10, longitude: 0))

        let points = generateQuadraticBezierPointsMK(
            start: start,
            control: control,
            end: end,
            segments: 10
        )

        XCTAssertEqual(points.count, 11)
        guard let first = points.first, let last = points.last else {
            XCTFail("Bezier points array is empty")
            return
        }

        XCTAssertEqual(first.latitude, start.coordinate.latitude, accuracy: 1e-6)
        XCTAssertEqual(last.longitude, end.coordinate.longitude, accuracy: 1e-6)

    }

    func testDistanceBetweenCoordinatesIsPositive() {
        let a = CLLocationCoordinate2D(latitude: 0, longitude: 0)
        let b = CLLocationCoordinate2D(latitude: 10, longitude: 10)

        let distance = distanceBetween(a, b)
        XCTAssertGreaterThan(distance, 0)
    }
}


// MARK: - RealtimeFFTTests
final class RealtimeFFTTests: XCTestCase {
    func testInitAndMagnitudes() {
        guard let fft = RealtimeFFT(size: 8) else {
            XCTFail("Failed to create RealtimeFFT")
            return
        }

        var samples: [Float] = [Float](repeating: 0, count: fft.n)
        samples[0] = 1.0

        let mags = samples.withUnsafeBufferPointer { ptr -> [Float] in
            return fft.magnitudes(from: ptr.baseAddress!)
        }

        XCTAssertEqual(mags.count, fft.n / 2)
        XCTAssertTrue(mags.max()! == 0.0)
    }
}
//
//// MARK: - SlotManagerTests
//final class SlotManagerTests: XCTestCase {
//    func testCurrentSlotsAndNextSlot() async {
//        let sm = SlotManager()
//
//        let txSlotsFT8Even = await sm.currentSlots(forTX: true, isFT4: false, evenCycle: true)
//        XCTAssertEqual(txSlotsFT8Even, [0.0, 30.0])
//
//        let rxSlotsFT8 = await sm.currentSlots(forTX: false, isFT4: false, evenCycle: false)
//        XCTAssertEqual(rxSlotsFT8, [0.0, 15.0, 30.0, 45.0])
//
//        let next = await sm.nextSlot(after: 10.0, forTX: true, isFT4: false, evenCycle: true)
//        XCTAssertEqual(next, 30.0)
//    }
//
//    func testWaitUntilNextSlotQuickPaths() async throws {
//        let logger = AppLogger(category: "TEST")
//        let result = try await SlotManager().waitUntilNextSlot(
//            taskName: "t",
//            logger: logger,
//            forTX: false,
//            isFT4: false,
//            evenCycle: true
//        )
//        XCTAssertTrue(result || result == false)
//    }
//}

// MARK: - ExtensionsTests
final class ExtensionsTests: XCTestCase {
    func testRotateLeft() {
        var a = [1, 2, 3, 4]
        a.rotateLeft(by: 2)
        XCTAssertEqual(a, [3, 4, 1, 2])
    }

    func testUTCISOFormatter() {
        let d = Date(timeIntervalSince1970: 0)
        let s = DateFormatter.utcISOFormatter.string(from: d)
        XCTAssertTrue(s.hasPrefix("1970-01-01T00:00:00"))
    }
}

// MARK: - AppLoggerTests
final class AppLoggerTests: XCTestCase {
    func testLoggerMethodsDontCrash() {
        let logger = AppLogger(category: "TEST")
        logger.info("info")
        logger.error("error")
        logger.debug("debug")
        XCTAssertTrue(true)
    }
}

// MARK: - FT8MessageTests
final class FT8MessageTests: XCTestCase {
    func testDetectMessageType() {
        XCTAssertEqual(FT8Message.detectMessageType(text: "CQ EA1AAA", parts: "CQ EA1AAA".uppercased().split(separator: " ")), .cq)
        XCTAssertEqual(FT8Message.detectMessageType(text: "F4XYZ EA1AAA -12", parts: "F4XYZ EA1AAA -12".uppercased().split(separator: " ")), .standardSignalReport)
        XCTAssertEqual(FT8Message.detectMessageType(text: "F4XYZ EA1AAA IM99", parts: "F4XYZ EA1AAA IM99".uppercased().split(separator: " ")), .gridExchange)
        XCTAssertEqual(FT8Message.detectMessageType(text: "EA1AAA K1ABC RR73", parts: "EA1AAA K1ABC RR73".uppercased().split(separator: " ")), .rr73)
        XCTAssertEqual(FT8Message.detectMessageType(text: "EA1AAA K1ABC RRR", parts: "EA1AAA K1ABC RRR".uppercased().split(separator: " ")), .rrr)
        XCTAssertEqual(FT8Message.detectMessageType(text: "Some random text", parts: "Some random text".uppercased().split(separator: " ")), .unknown)
    }

    func testIsForMe() {
        UserDefaults.standard.set("EA1AAA", forKey: "callsign")

        var participants = FT8Message.parseParticipants(parts: "CQ EA1AAA".uppercased().split(separator: " "))
        XCTAssertTrue(
            FT8Message.isForMe(
                participants: participants,
                myCallsign: "EA1AAA",
                isTX: false
            )
        )

        participants = FT8Message.parseParticipants(parts: "F4XYZ EA1AAA -12".uppercased().split(separator: " "))
        XCTAssertTrue(
            FT8Message.isForMe(
                participants: participants,
                myCallsign: "EA1AAA",
                isTX: false
            )
        )

        participants = FT8Message.parseParticipants(parts: "CQ K1ABC".uppercased().split(separator: " "))
        XCTAssertFalse(
            FT8Message.isForMe(
                participants: participants,
                myCallsign: "EA1AAA",
                isTX: false
            )
        )

        // Adapted versions of the original string-based test cases
        participants = FT8Message.parseParticipants(parts: "CQ EA1AAA".uppercased().split(separator: " "))
        XCTAssertTrue(
            FT8Message.isForMe(
                participants: participants,
                myCallsign: "EA1AAA",
                isTX: false
            )
        )

        participants = FT8Message.parseParticipants(parts: "F4XYZ EA1AAA -12".uppercased().split(separator: " "))
        XCTAssertTrue(
            FT8Message.isForMe(
                participants: participants,
                myCallsign: "EA1AAA",
                isTX: false
            )
        )

        participants = FT8Message.parseParticipants(parts: "F4XYZ EB1BBB -12".uppercased().split(separator: " "))
        XCTAssertFalse(
            FT8Message.isForMe(
                participants: participants,
                myCallsign: "EA1AAA",
                isTX: false
            )
        )
    }


    func testBandProperties() {
        // FT8 frequency for 10m band
        XCTAssertEqual(
            FT8Message.Band.band10m.frequency(for: .ft8),
            28_074_000
        )

        // Unknown band has no frequency
        XCTAssertNil(
            FT8Message.Band.unknown.frequency(for: .ft8)
        )

        // Valid bands list excludes .unknown
        XCTAssertTrue(
            FT8Message.Band.validBands.contains(.band20m)
        )
    }

}

// MARK: - FT8MessageComposerTests
final class FT8MessageComposerTests: XCTestCase {
    func testGenerateMessagesFormatting() {
        UserDefaults.standard.removeObject(forKey: "cqModifier")
        let c = FT8MessageComposer()
        let msgs = c.generateMessages(
            callsign: "ea1aaa",
            locator: "im99",
            dxCallsign: "k1abc",
            dxLocator: "io91",
            snrToSend: 5.4
        )
        XCTAssertTrue(msgs.contains("CQ EA1AAA IM99"))
        XCTAssertTrue(msgs.contains("K1ABC EA1AAA IM99"))
        XCTAssertTrue(msgs.contains("K1ABC EA1AAA +05"))

        let msgsNaN = c.generateMessages(callsign: "E1", locator: "IM99", dxCallsign: "", dxLocator: "", snrToSend: Double.nan)
        XCTAssertTrue(msgsNaN.contains("CQ E1 IM99"))
        UserDefaults.standard.removeObject(forKey: "cqModifier")
    }
    
    func testGenerateMessagesWithActivationModifiers() {
        let c = FT8MessageComposer()
        
        // Test POTA
        UserDefaults.standard.set("POTA", forKey: "cqModifier")
        let potaMsgs = c.generateMessages(
            callsign: "EA4IQL",
            locator: "IN80",
            dxCallsign: "K1ABC",
            dxLocator: "FN31",
            snrToSend: -10.0
        )
        XCTAssertTrue(potaMsgs[0].contains("CQ POTA EA4IQL"))
//        XCTAssertTrue(potaMsgs[0].contains("IN80"))
        
        // Test SOTA
        UserDefaults.standard.set("SOTA", forKey: "cqModifier")
        let sotaMsgs = c.generateMessages(
            callsign: "EA4IQL",
            locator: "IN80",
            dxCallsign: "K1ABC",
            dxLocator: "FN31",
            snrToSend: -10.0
        )
        XCTAssertTrue(sotaMsgs[0].contains("CQ SOTA EA4IQL"))
        
        // Test WWFF
        UserDefaults.standard.set("WWFF", forKey: "cqModifier")
        let wwffMsgs = c.generateMessages(
            callsign: "EA4IQL",
            locator: "IN80",
            dxCallsign: "K1ABC",
            dxLocator: "FN31",
            snrToSend: -10.0
        )
        XCTAssertTrue(wwffMsgs[0].contains("CQ WWFF EA4IQL"))
        UserDefaults.standard.removeObject(forKey: "cqModifier")
        
        // Test IOTA
        UserDefaults.standard.set("IOTA", forKey: "cqModifier")
        let iotaMsgs = c.generateMessages(
            callsign: "EA4IQL",
            locator: "IN80",
            dxCallsign: "K1ABC",
            dxLocator: "FN31",
            snrToSend: -10.0
        )
        XCTAssertTrue(iotaMsgs[0].contains("CQ IOTA EA4IQL"))
        
        // Clean up
        UserDefaults.standard.removeObject(forKey: "cqModifier")
    }
    
    func testGenerateMessagesWithGeographicFilters() {
        let c = FT8MessageComposer()
        let geographicFilters = ["DX", "EU", "NA", "SA", "AF", "AS", "OC", "ANT"]
        
        for filter in geographicFilters {
            UserDefaults.standard.set(filter, forKey: "cqModifier")
            let msgs = c.generateMessages(
                callsign: "EA4IQL",
                locator: "IN80",
                dxCallsign: "K1ABC",
                dxLocator: "FN31",
                snrToSend: -10.0
            )
            XCTAssertTrue(msgs[0].contains("CQ \(filter) EA4IQL"), "Geographic filter \(filter) not in CQ message")
//            XCTAssertTrue(msgs[0].contains("IN80"), "Grid missing for \(filter)")
        }
        
        UserDefaults.standard.removeObject(forKey: "cqModifier")
    }
    
    func testGenerateMessagesWithoutModifier() {
        let c = FT8MessageComposer()
        
        // Test with NONE
        UserDefaults.standard.set("NONE", forKey: "cqModifier")
        let noneMsg = c.generateMessages(
            callsign: "EA4IQL",
            locator: "IN80",
            dxCallsign: "K1ABC",
            dxLocator: "FN31",
            snrToSend: -10.0
        )
        XCTAssertTrue(noneMsg[0] == "CQ EA4IQL IN80")
        XCTAssertFalse(noneMsg[0].contains("CQ NONE"))
        
        // Test with no key set
        UserDefaults.standard.removeObject(forKey: "cqModifier")
        let noKeyMsg = c.generateMessages(
            callsign: "EA4IQL",
            locator: "IN80",
            dxCallsign: "K1ABC",
            dxLocator: "FN31",
            snrToSend: -10.0
        )
        XCTAssertTrue(noKeyMsg[0] == "CQ EA4IQL IN80")
    }
    
    func testGenerateMessagesIgnoresInvalidModifier() {
        let c = FT8MessageComposer()
        
        // Set an invalid modifier
        UserDefaults.standard.set("INVALID", forKey: "cqModifier")
        let msgs = c.generateMessages(
            callsign: "EA4IQL",
            locator: "IN80",
            dxCallsign: "K1ABC",
            dxLocator: "FN31",
            snrToSend: -10.0
        )
        // Should generate normal CQ without invalid modifier
        XCTAssertTrue(msgs[0] == "CQ EA4IQL IN80")
        XCTAssertFalse(msgs[0].contains("INVALID"))
        
        UserDefaults.standard.removeObject(forKey: "cqModifier")
    }
}

// MARK: - FT8CallsignWithSuffixTests
// In FT8/FT4, any callsign with "/" is valid (no closed list of modifiers)
// User can directly enter callsigns like EA4IQL/P, EA4IQL/MM, EA4IQL/CUSTOM
final class FT8CallsignWithSuffixTests: XCTestCase {
    
    func testGenerateMessagesWithCallsignSuffix() {
        let c = FT8MessageComposer()
        
        // When user enters callsign with suffix directly
        let msgs = c.generateMessages(
            callsign: "EA4IQL/P",
            locator: "IN80",
            dxCallsign: "K1ABC",
            dxLocator: "FN31",
            snrToSend: -10.0
        )
        
        XCTAssertTrue(msgs[0].contains("EA4IQL/P"), "CQ message should contain /P")
        XCTAssertTrue(msgs[1].contains("EA4IQL/P"), "Grid exchange should contain /P")
        XCTAssertTrue(msgs[2].contains("EA4IQL/P"), "Report should contain /P")
        XCTAssertTrue(msgs[4].contains("EA4IQL/P"), "RRR should contain /P")
    }
    
    func testGenerateMessagesWithCommonCallsignSuffixes() {
        let c = FT8MessageComposer()
        let suffixes = ["/P", "/M", "/MM", "/AM", "/QRP", "/R", "/1", "/ABC"]
        
        for suffix in suffixes {
            let msgs = c.generateMessages(
                callsign: "EA4IQL\(suffix)",
                locator: "IN80",
                dxCallsign: "K1ABC",
                dxLocator: "FN31",
                snrToSend: -10.0
            )
            
            let expectedCallsign = "EA4IQL\(suffix)"
            XCTAssertTrue(msgs[0].contains(expectedCallsign), "CQ should contain \(suffix)")
            XCTAssertTrue(msgs[1].contains(expectedCallsign), "Grid exchange should contain \(suffix)")
            XCTAssertTrue(msgs[2].contains(expectedCallsign), "Report should contain \(suffix)")
        }
    }

}


// MARK: - FT8EngineTests
final class FT8EngineTests: XCTestCase {
    func testGenerateFT8ReturnsData() {
        let engine = ft8_Engine()
        let data = engine.generateFT8("CQ EA1AAA IM99", frequency: 1400.0, isFT4: false, toFile: nil)
        XCTAssertNotNil(data)
        if let d = data {
            XCTAssertTrue(d.count > 0)
        } else if let nsd = data as? NSData {
            XCTAssertTrue(nsd.length > 0)
        }
    }

    func testDecodeNilDoesNotCrash() {
        let engine = ft8_Engine()
        let decoded = engine.decode(nil, isFT4: false)
        XCTAssertNotNil(decoded)
        XCTAssertTrue(decoded.count >= 0)
    }
}

// MARK: - ValidatorsTests
final class ValidatorsTests: XCTestCase {
    func testIsValidCallsign() {
        XCTAssertTrue(isValidCallsign("EA1AAA"))
        XCTAssertFalse(isValidCallsign("???"))
    }
    
    func testIsValidCallsignWithSuffix() {
        // In FT8/FT4, any suffix with "/" is valid - no closed list
        XCTAssertTrue(isValidCallsign("EA1AAA/P"))      // Portable
        XCTAssertTrue(isValidCallsign("EA1AAA/M"))      // Mobile
        XCTAssertTrue(isValidCallsign("EA1AAA/MM"))     // Maritime Mobile
        XCTAssertTrue(isValidCallsign("EA1AAA/AM"))     // Aeronautical Mobile
        XCTAssertTrue(isValidCallsign("EA1AAA/QRP"))    // Low power
        XCTAssertTrue(isValidCallsign("EA1AAA/R"))      // Repeater
        XCTAssertTrue(isValidCallsign("EA1AAA/1"))      // Numeric suffix
        XCTAssertTrue(isValidCallsign("EA1AAA/ABC"))    // Custom suffix
        XCTAssertTrue(isValidCallsign("EA1AAA/TEST"))   // Multi-char suffix
        XCTAssertTrue(isValidCallsign("W1A/P"))         // Short callsign with suffix
    }

    func testIsValidLocator() {
        XCTAssertTrue(isValidLocator("IM99"))
        XCTAssertFalse(isValidLocator("RR73"))
        XCTAssertFalse(isValidLocator("ABC"))
    }

    func testIsSignalReport() {
        XCTAssertTrue(isSignalReport(Substring("12")))
        XCTAssertTrue(isSignalReport(Substring("R-12")))
        XCTAssertFalse(isSignalReport(Substring("abc")))
    }
}

// MARK: - WaterfallViewModelTests
@MainActor
final class WaterfallViewModelTests: XCTestCase {
    func testInitAndBasicAPIs() {
        let vm = WaterfallViewModel(sampleRate: 12000, waterfallFFTSize: 16, waterfallRows: 4, isFT4: false)

        XCTAssertEqual(vm.width, 8)
        XCTAssertEqual(vm.height, 4)

        XCTAssertEqual(vm.frequencyAtPixel(x: 1, width: 0), 0)
        XCTAssertGreaterThan(vm.frequencyAtPixel(x: 1, width: 10), 0)

        vm.updateConfig { c in
            c.waterfallMaxRows = 10
        }
        XCTAssertLessThanOrEqual(vm.height, WaterfallViewModel.Config.absoluteMaxRows)
    }

    func testUpdateWaterfallAddsLabelsAndTimestamps() {
        let vm = WaterfallViewModel(sampleRate: 12000, waterfallFFTSize: 16, waterfallRows: 4, isFT4: false)
        vm.visibleRows = 1
        vm.addVerticalLabel(text: "L", frequency: 1000.0)

        let mags = [Float](repeating: 0.5, count: vm.width)
        vm.updateWaterfall(from: mags)

        let ts = vm.timestampsForOverlay(height: 1)
        XCTAssertTrue(ts.count >= 0)

        let labels = vm.verticalLabelsForOverlay(height: 1)
        XCTAssertTrue(labels.count >= 0)
    }
}
